package main

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func main() {
	root := flag.String("root", ".", "cna-go repository root")
	contractFile := flag.String("contract", "tools/api_compat/reference/xna40-windows-runtime-contract.json", "XNA reference contract path relative to root")
	mappingFile := flag.String("mapping", "tools/api_compat/mapping-rules.json", "mapping rules path relative to root")
	reportFile := flag.String("report", "docs/generated/api-compat-report.json", "JSON report path relative to root; empty disables writing")
	missingFile := flag.String("missing", "docs/generated/missing-type-inventory.md", "Markdown inventory path relative to root; empty disables writing")
	mode := flag.String("mode", "strict", "strict, leak-only, or report")
	flag.Parse()

	if err := run(*root, *contractFile, *mappingFile, *reportFile, *missingFile, *mode); err != nil {
		fmt.Fprintln(os.Stderr, "api-compat:", err)
		os.Exit(1)
	}
}

func run(root, contractFile, mappingFile, reportFile, missingFile, mode string) error {
	if mode != "strict" && mode != "leak-only" && mode != "report" {
		return fmt.Errorf("unsupported mode %q", mode)
	}
	absoluteRoot, err := filepath.Abs(root)
	if err != nil {
		return err
	}
	contractBytes, err := os.ReadFile(resolvePath(absoluteRoot, contractFile))
	if err != nil {
		return err
	}
	var reference contract
	if err := json.Unmarshal(contractBytes, &reference); err != nil {
		return fmt.Errorf("parse contract: %w", err)
	}
	if reference.SchemaVersion != 2 || reference.Profile != "XNA 4.0 Windows runtime" {
		return fmt.Errorf("unexpected reference contract schema/profile: %d %q", reference.SchemaVersion, reference.Profile)
	}
	mappingBytes, err := os.ReadFile(resolvePath(absoluteRoot, mappingFile))
	if err != nil {
		return err
	}
	allowlistEntries, err := mappingAllowlistEntries(mappingBytes)
	if err != nil {
		return err
	}
	expected, err := buildExpected(reference)
	if err != nil {
		return err
	}
	if expected.ReferenceTypes != 257 || expected.ReferenceMembers != 2964 {
		return fmt.Errorf("reference admission failed: got %d types/%d members", expected.ReferenceTypes, expected.ReferenceMembers)
	}
	if expected.ExpectedGoTypes != 257 || expected.ExpectedGoMembers != 3243 {
		return fmt.Errorf("mapping count admission failed: got %d types/%d members", expected.ExpectedGoTypes, expected.ExpectedGoMembers)
	}
	actual, err := extractActual(absoluteRoot)
	if err != nil {
		return err
	}
	if len(actual.TypeErrors) != 0 {
		return fmt.Errorf("Go type-check admission produced %d errors; first: %s", len(actual.TypeErrors), actual.TypeErrors[0])
	}
	result := verify(expected, actual, allowlistEntries, mode, sha256Hex(contractBytes), sha256Hex(mappingBytes))
	if reportFile != "" {
		if err := writeJSON(resolvePath(absoluteRoot, reportFile), result); err != nil {
			return err
		}
	}
	if missingFile != "" {
		if err := writeMissingInventory(resolvePath(absoluteRoot, missingFile), result); err != nil {
			return err
		}
	}
	printSummary(result)

	switch mode {
	case "strict":
		if result.Summary["TOTAL_DIAGNOSTICS"] != 0 {
			return errors.New("strict structural verification is red (expected while the binding is incomplete)")
		}
	case "leak-only":
		if result.Summary["INTERNAL_TYPE_LEAK"]+result.Summary["RAW_HANDLE_LEAK"]+result.Summary["PUBLIC_NATIVE_FFI_LEAK"] != 0 {
			return errors.New("public native-state leak verification failed")
		}
	}
	return nil
}

func resolvePath(root, name string) string {
	if filepath.IsAbs(name) {
		return name
	}
	return filepath.Join(root, name)
}

func mappingAllowlistEntries(data []byte) (int, error) {
	var value map[string]json.RawMessage
	if err := json.Unmarshal(data, &value); err != nil {
		return 0, fmt.Errorf("parse mapping rules: %w", err)
	}
	raw, ok := value["allowlist"]
	if !ok {
		return 0, nil
	}
	var entries []json.RawMessage
	if err := json.Unmarshal(raw, &entries); err != nil {
		return 0, fmt.Errorf("parse mapping allowlist: %w", err)
	}
	return len(entries), nil
}

func writeJSON(filename string, value any) error {
	data, err := json.MarshalIndent(value, "", "  ")
	if err != nil {
		return err
	}
	data = append(data, '\n')
	if err := os.MkdirAll(filepath.Dir(filename), 0o755); err != nil {
		return err
	}
	return os.WriteFile(filename, data, 0o644)
}

func writeMissingInventory(filename string, result report) error {
	var output strings.Builder
	output.WriteString("# Generated missing-type inventory\n\n")
	output.WriteString("Generated by `go run ./tools/api_compat --mode report`. Do not edit by hand.\n\n")
	fmt.Fprintf(&output, "- Complete types: %d\n- Partial types: %d\n- Missing types: %d\n\n", len(result.CompleteTypes), len(result.PartialTypes), len(result.MissingTypes))
	output.WriteString("## Complete types\n\n")
	if len(result.CompleteTypes) == 0 {
		output.WriteString("None.\n\n")
	} else {
		for _, name := range result.CompleteTypes {
			fmt.Fprintf(&output, "- `%s`\n", name)
		}
		output.WriteByte('\n')
	}
	output.WriteString("## Partial types\n\n")
	if len(result.PartialTypes) == 0 {
		output.WriteString("None.\n\n")
	} else {
		for _, item := range result.PartialTypes {
			fmt.Fprintf(&output, "### `%s`\n\n", item.XNA)
			for _, missing := range item.MissingMembers {
				fmt.Fprintf(&output, "- `%s`\n", missing)
			}
			output.WriteByte('\n')
		}
	}
	output.WriteString("## Missing types\n\n")
	for _, name := range result.MissingTypes {
		fmt.Fprintf(&output, "- `%s`\n", name)
	}
	if err := os.MkdirAll(filepath.Dir(filename), 0o755); err != nil {
		return err
	}
	return os.WriteFile(filename, []byte(output.String()), 0o644)
}

func printSummary(result report) {
	order := []string{
		"REFERENCE_TYPES", "REFERENCE_MEMBERS", "EXPECTED_GO_TYPES", "EXPECTED_GO_MEMBERS",
		"TARGET_TYPES", "TARGET_MEMBERS", "TOTAL_DIAGNOSTICS", "MISSING_TYPE", "MISSING_MEMBER",
		"COMPLETE_TYPES", "PARTIAL_TYPES", "MISSING_TYPES",
	}
	order = append(order, diagnosticCategories[2:]...)
	seen := make(map[string]bool)
	for _, key := range order {
		if seen[key] {
			continue
		}
		seen[key] = true
		fmt.Printf("%s=%d\n", key, result.Summary[key])
	}
}

func sha256Hex(value []byte) string {
	sum := sha256.Sum256(value)
	return hex.EncodeToString(sum[:])
}

func sortedKeys(values map[string]int) []string {
	result := make([]string, 0, len(values))
	for key := range values {
		result = append(result, key)
	}
	sort.Strings(result)
	return result
}
